export const formConstants = {
	ADD_CHANGE: 'ADD_CHANGE',
	EDIT_FORM_PENDING: 'EDIT_FORM_PENDING',
	EDIT_FORM_SUCCESS: 'EDIT_FORM_SUCCESS',
	HANDLE_SUBMIT_REQUEST: 'HANDLE_SUBMIT_REQUEST',
	HANDLE_SUBMIT_SUCCESS: 'HANDLE_SUBMIT_SUCCESS',
	HANDLE_SUBMIT_FAILURE: 'HANDLE_SUBMIT_FAILURE',
	HANDLE_UPDATE_REQUEST: 'HANDLE_UPDATE_REQUEST',
	HANDLE_UPDATE_SUCCESS: 'HANDLE_UPDATE_SUCCESS',
	HANDLE_UPDATE_FAILURE: 'HANDLE_UPDATE_FAILURE',
	HANDLE_LOAD_FAILURE: 'HANDLE_LOAD_FAILURE',
	LOAD_EDIT_FORM: 'LOAD_EDIT_FORM',
	SET_UP_EDIT_FORM: 'SET_UP_EDIT_FORM',
}